# eureka:
#   instance:
#     lease-renewal-interval-in-seconds: 10
#     lease-expiration-duration-in-seconds: 30
# #    healthcheck:
# #      enabled: true #开启健康检查（需要spring-boot-starter-actuator依赖）
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
spring:
  redis:
    host: 132.232.175.240
test: this is a test message.
